name: suraksha_drive
description: AI-powered driver drowsiness detection. Apni suraksha, apne haath!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  audioplayers: ^6.0.0
  vibration: ^2.0.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/audio/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 26
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"